repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [feat, fix, ci, chore, test] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]